version: "2"

run:
  timeout: 3m
  modules-download-mode: readonly

linters:
  enable:
    - errname
    - gosec
    - sqlclosecheck
    - stylecheck
    - unconvert
    - unparam

formatters:
  enable:
    - gci
    - gofmt
